### ISSUE TITLE
Need to update doc to deploy on GKE with istio addon

### ISSUE THREAD

**Issue by raffomartini** [kiali/kiali.io#103]
I was following the instructions to install kiali on https://www.kiali.io/gettingstarted/#_getting_started_on_kubernetes
and getting into an error.

After logging this [ticket](https://github.com/kiali/kiali/issues/870#issuecomment-466771255) I realized that I was missing a prerequisite to install istio on GKE, that is also needed to install Kiali.
```
$ kubectl create clusterrolebinding cluster-admin-binding \
    --clusterrole=cluster-admin \
    --user=$(gcloud config get-value core/account)
```

**I believe this should be mentioned in the Kiali doc to help people in the same situation.**

**Comment by jmazzitelli** [comment]
We could mention in the docs that the user needs to make sure they perform their cluster-specific instructions when installing Istio prior to installing Kiali. I would not duplicate the same Istio docs, I would just link to them. Linking to this page and telling the user to make sure these additional instructions were performed should be sufficient: https://istio.io/docs/setup/kubernetes/platform-setup/

**Comment by lentzi90** [comment]
This is also not relevant for version 1.12.x and newer. See https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#iam-rolebinding-bootstrap
