### ISSUE TITLE
Invalid cert for kiali.io

### ISSUE THREAD

**Issue by j00bar** [kiali/kiali.io#37]
It looks like https://kiali.io/ is using the redhat.com wildcard cert, which is obviously invalid.

![image](https://user-images.githubusercontent.com/166664/45932562-f2195900-bf4b-11e8-9a6e-0eb815e4aff6.png)

**Comment by mtho11** [comment]
Confirmed. Thank you @j00bar!

**Comment by mtho11** [comment]
Created Jira Issue for this: https://github.com/kiali/kiali.io/issues/37

**Comment by mwringe** [comment]
https://www.kiali.io will work fine, but not http://kiali.io. We need to work on getting our certificates to work without the 'www' in front.

**Comment by j00bar** [comment]
The cert for www.kiali.io looks like it will work for both, however that's not the cert that's being presented for kiali.io -- fwiw (/me is jag@redhat) I've seen this on other things where the A record points to `redirect.redhat.com`, e.g. ansiblefest.com has the same problem and resolves to the same IP address.

**Comment by jmazzitelli** [comment]
We really need to fix this - or else people are going to keep opening issues for it :)

kiali issue: https://github.com/kiali/kiali/issues/510

mailing list: https://groups.google.com/forum/#!topic/kiali-dev/IoLb15loxY4/discussion

**Comment by mtho11** [comment]
@jmazzitelli we can close this issue now correct?

**Comment by j00bar** [comment]
I do not see that this issue has been fixed.

**Comment by mtho11** [comment]
Thanks for your feedback @j00bar

**Comment by xeviknal** [comment]
@j00bar We've got finally changes in our DNS. Do you mind checking if this is still a problem for you, please? Thanks!

**Comment by j00bar** [comment]
Huzzah! Proper cert confirmed:

![image](https://user-images.githubusercontent.com/166664/66132142-9eac0300-e5c2-11e9-8f5c-d1a872644dd3.png)

Thanks, y'all!
