### ISSUE TITLE
travel demo tutorial minor enhancement suggestion..

### ISSUE THREAD

**Issue by eitansuez** [kiali/kiali.io#520]
hi there, i'm working through the travel demo tutorial on the kiali web site.

in the observe section, https://kiali.io/docs/tutorials/travels/04-observe/
i'd like to suggest that,
instead of deleting and redeploying the workloads,
use kubectl rollout restart, like so:

k rollout restart deploy -n travel-portal
k rollout restart deploy -n travel-agency

**Comment by jshaughn** [comment]
Sorry, @eitansuez, we didn't see this.  Did you close because of no-response or because you decided against the change?

**Comment by eitansuez** [comment]
no worries.  i closed because i submitted a [PR](https://github.com/kiali/kiali.io/pull/521) that [i thought] was merged that addressed this.  i should have been more specific.  but now i see i forgot to merge it.  reopening..

**Comment by eitansuez** [comment]
so it looks like the workflow requires approval..

**Comment by eitansuez** [comment]
ok, pr merged, i think we can close this issue now. :-)
