### ISSUE TITLE
The animation of top navigation bar is too slow

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali.io#95]
The animation of the top bar when scrolling down and up slows down the whole page. Although I am not sure if it's only on my environment.

Also the very top bar with github, youtube icons seems redundant and breaks the design cleanness.

![screenshot of kiali](https://user-images.githubusercontent.com/5618424/51545735-e5a5fe00-1e62-11e9-9107-37dfa5f56a06.png)

**Comment by xeviknal** [comment]
Closing this issue because of the re-styling of kiali.io.
Thanks anyway for the ticket :)
